### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by HevenLiu** [xCss/Valine#4]
TypeError: Cannot read property 'slice' of undefined
Valine:1.1.6

**Comment by xCss** [comment]
你好，能提供一下<安装方式(代码)>、<浏览器环境>等。抱歉，目前我手机，暂无法定位你的问题。
大概明晚能上电脑。
发送手机。
-------- 原始信息 --------由： Heven <notifications@github.com> 日期: 2017/8/20  14:31  (GMT+08:00) 收件人： xCss/Valine <Valine@noreply.github.com> 抄送： Subscribed <subscribed@noreply.github.com> 主题： [xCss/Valine] TypeError (#4) 
TypeError: Cannot read property 'slice' of undefined

Valine:1.1.6

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xCss/Valine","title":"xCss/Valine","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xCss/Valine"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"TypeError (#4)"}],"action":{"name":"View Issue","url":"https://github.com/xCss/Valine/issues/4"}}}

**Comment by xCss** [comment]
@HevenLiu 你好，目前就你上面提供的错误信息：  
```js
TypeError: Cannot read property 'slice' of undefined
Valine:1.1.6
```
我是不能够定位错误的详细位置的。
能提供一下`安装步骤`、`浏览器环境`和`错误截图`吗？

**Comment by castboxer** [comment]
我也出现了同样的问题，我的浏览器是mac下的chrome， 安装步骤就是在theme中讲app_id， app_key加进去，之后hexo g提交就出现这种情况
